### ISSUE TITLE
 combine_cds dropping some essential gene information

### ISSUE THREAD

**Issue by amar1406** [cole-trapnell-lab/monocle3#276]
**Describe the bug**
I noticed a weird behavior in the **combine_cds** function. It drops the gene id & gene short names for a portion of genes, and this sometimes significantly affects the clustering to a level that they no longer cluster together even when we know they are biologically similar and from the same batch.

This only happens **if there's a difference in the number of genes or a general mismatch in gene list** present in each dataset I want to combine while "keeping all the genes" by default.

An example:-

CDS1 (Dim: 58310 13370 )
CDS2 (Dim: 42211 28188 )

Combined_CDS (Dim: 59154 41558 )
but some gene_short_names are replaced by NA (like in this screenshot below)
![image](https://user-images.githubusercontent.com/51770053/72213652-44ff8280-34a7-11ea-92f1-77549b006a14.png)

**To Reproduce**
The order of combing does affect the number of NA
- `Combined_CDS <- combine_cds(list(CDS1 ,CDS2 ))`
in this specific case, there's 889 replaced with NA

- `Combined_CDS <- combine_cds(list(CDS2 ,CDS1 ))`
in this specific case, there's 16,943 replaced with NA

- In case I arbitrarily remove genes to make them equal in numbers in both CDS, I still get NAs, but this time the combining order doesn't matter. Suggesting that it has to do with the mismatch particularly.

**Expected behavior**
I expected this function to keep all genes, but for now, I use "keep_all_genes = F" as a workaround, with that, there are no issues, but I hope this gets addressed! Thank you!

**sessionInfo():**
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] splines   stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reshape2_1.4.3              gridExtra_2.3               RColorBrewer_1.1-2          Matrix.utils_0.9.7         
 [5] dplyr_0.8.3                 tidyr_1.0.0                 monocle_2.12.0              DDRTree_0.1.5              
 [9] irlba_2.3.3                 VGAM_1.1-2                  ggplot2_3.2.1               Matrix_1.2-17              
[13] biomaRt_2.40.5              monocle3_0.2.0              SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.1
[17] DelayedArray_0.10.0         BiocParallel_1.18.1         matrixStats_0.55.0          GenomicRanges_1.36.1       
[21] GenomeInfoDb_1.20.0         IRanges_2.18.3              S4Vectors_0.22.1            Biobase_2.44.0             
[25] BiocGenerics_0.30.0        

loaded via a namespace (and not attached):
 [1] Rtsne_0.15               ggbeeswarm_0.6.0         colorspace_1.4-1         grr_0.9.5                ellipsis_0.3.0          
 [6] XVector_0.24.0           BiocNeighbors_1.2.0      rstudioapi_0.10          farver_2.0.1             ggrepel_0.8.1           
[11] bit64_0.9-7              fansi_0.4.0              AnnotationDbi_1.46.1     RSpectra_0.15-0          codetools_0.2-16        
[16] docopt_0.6.1             scater_1.12.2            zeallot_0.1.0            speedglm_0.3-2           RhpcBLASctl_0.18-205    
[21] cluster_2.1.0            pheatmap_1.0.12          uwot_0.1.4               compiler_3.6.1           httr_1.4.1              
[26] backports_1.1.5          assertthat_0.2.1         lazyeval_0.2.2           cli_1.1.0                limma_3.40.6            
[31] BiocSingular_1.0.0       prettyunits_1.0.2        tools_3.6.1              rsvd_1.0.2               igraph_1.2.4.1          
[36] gtable_0.3.0             glue_1.3.1               GenomeInfoDbData_1.2.1   RANN_2.6.1               Rcpp_1.0.3              
[41] slam_0.1-46              vctrs_0.2.0              DelayedMatrixStats_1.6.1 lmtest_0.9-37            stringr_1.4.0           
[46] lifecycle_0.1.0          XML_3.98-1.20            zlibbioc_1.30.0          MASS_7.3-51.4            zoo_1.8-6               
[51] scales_1.1.0             hms_0.5.2                memoise_1.1.0            leidenbase_0.1.0         fastICA_1.2-2           
[56] stringi_1.4.3            RSQLite_2.1.2            densityClust_0.3         rlang_0.4.2              pkgconfig_2.0.3         
[61] bitops_1.0-6             qlcMatrix_0.9.7          lattice_0.20-38          purrr_0.3.3              labeling_0.3            
[66] bit_1.1-14               tidyselect_0.2.5         RcppAnnoy_0.0.14         plyr_1.8.4               magrittr_1.5            
[71] R6_2.4.1                 combinat_0.0-8           DBI_1.0.0                pillar_1.4.2             withr_2.1.2             
[76] RCurl_1.95-4.12          tibble_2.1.3             batchelor_1.0.1          crayon_1.3.4             utf8_1.1.4              
[81] KernSmooth_2.23-16       viridis_0.5.1            progress_1.2.2           grid_3.6.1               blob_1.2.0              
[86] FNN_1.1.3                HSMMSingleCell_1.4.0     sparsesvd_0.2            digest_0.6.23            pbmcapply_1.5.0         
[91] RcppParallel_4.4.4       munsell_0.5.0            beeswarm_0.2.3           viridisLite_0.3.0        vipor_0.4.5

**Comment by hpliner** [comment]
Hello, Thanks for this well-described report. I believe I have identified the issue and have pushed a fix to the develop branch of the package. Go ahead and reinstall the development branch by running:

`devtools::install_github('cole-trapnell-lab/monocle3', ref='develop')`

Let me know if this issue persists and I will reopen.

**Comment by amar1406** [comment]
Thank you very much, it's working as intended!

Another minor issue just appeared. The following error is triggered **if there are columns in the rowData unique** to one dataset but not the other
`Error in if (confs > 0) { : missing value where TRUE/FALSE needed`

In this case, I expect  NA to normally appear in those new columns

**Comment by hpliner** [comment]
@amar1406 Glad it seems like it's working. I just fixed (hopefully) this last issue, give it a try!

**Comment by amar1406** [comment]
Thank you. and sorry for getting back to you this late. 

Unfortunately, the issue is not solved yet. I assumed the issue was with the annotation, but it looks like it has to do with the count matrix. In the second cds object being added, the counts can be assigned to the wrong gene

It's difficult for me to explain, but I hope you can follow this example in the screenshot & perhaps you can identify what's going on.
Thanks!

![Screenshot (26)](https://user-images.githubusercontent.com/51770053/74591538-adbdab80-4fcd-11ea-9425-e1772a4894a8.png)


```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.8.3                 ggplot2_3.2.1               monocle3_0.2.1.3            SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.1 DelayedArray_0.10.0         BiocParallel_1.18.1        
 [8] matrixStats_0.55.0          GenomicRanges_1.36.1        GenomeInfoDb_1.20.0         IRanges_2.18.3              S4Vectors_0.22.1            Biobase_2.44.0              BiocGenerics_0.30.0        
[15] tidyr_1.0.2                

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3             plyr_1.8.5             compiler_3.6.1         pillar_1.4.3           XVector_0.24.0         viridis_0.5.1          bitops_1.0-6           tools_3.6.1            zlibbioc_1.30.0       
[10] viridisLite_0.3.0      lifecycle_0.1.0        tibble_2.1.3           gtable_0.3.0           lattice_0.20-38        pkgconfig_2.0.3        rlang_0.4.2            Matrix_1.2-17          rstudioapi_0.11       
[19] gridExtra_2.3          GenomeInfoDbData_1.2.1 withr_2.1.2            stringr_1.4.0          vctrs_0.2.2            tidyselect_0.2.5       grid_3.6.1             glue_1.3.1             R6_2.4.1              
[28] reshape2_1.4.3         purrr_0.3.3            magrittr_1.5           scales_1.1.0           assertthat_0.2.1       colorspace_1.4-1       stringi_1.4.5          RCurl_1.98-1.1         lazyeval_0.2.2        
[37] munsell_0.5.0          crayon_1.3.4  
```

**Comment by hpliner** [comment]
Hi @amar1406, Ok, I think I finally tracked down the bug. If you go ahead and download the latest develop branch (0.2.1.6), I think it should be working now. Thanks for your detailed reports!

**Comment by hpliner** [comment]
I believe this is fixed. Reopen if not!
